var NW_WINERIES=[
{id:"opus",name:"Opus One",town:"Oakville",ava:"Oakville AVA",tags:["Modern","Icon"],blurb:"Mondavi × Rothschild's circular limestone estate; iconic Bordeaux-style blend with valley views. By appointment.",url:"https://www.opusonewinery.com"},
{id:"montelena",name:"Château Montelena",town:"Calistoga",ava:"Calistoga AVA",tags:["Historic","Icon"],blurb:"1976 Judgment of Paris Chardonnay winner; stone château above Jade Lake. Est. 1882.",url:"https://montelena.com"},
{id:"amorosa",name:"Castello di Amorosa",town:"Calistoga",ava:"Calistoga AVA",tags:["Castle"],blurb:"Medieval-style Tuscan castle — moat, drawbridge, frescoed great hall. Tours daily.",url:"https://castellodiamorosa.com"},
{id:"mondavi",name:"Robert Mondavi Winery",town:"Oakville",ava:"Oakville AVA",tags:["Historic","Icon"],blurb:"The winery that defined modern Napa; To Kalon Cabernet and Fumé Blanc since 1966. Great first-timer stop.",url:"https://www.robertmondaviwinery.com"},
{id:"carneros",name:"Domaine Carneros",town:"Napa",ava:"Carneros AVA",tags:["Sparkling","Castle"],blurb:"Taittinger's château; traditional-method sparkling and Pinot Noir on a terrace over the vines. Relaxed, gardens.",url:"https://www.domainecarneros.com"},
{id:"stagsleap",name:"Stag's Leap Wine Cellars",town:"Napa",ava:"Stags Leap District",tags:["Cave Tour","Icon"],blurb:"1976 Judgment of Paris red-wine champion; Cask 23 and elegant estate caves.",url:"https://www.cask23.com"},
{id:"inglenook",name:"Inglenook",town:"Rutherford",ava:"Rutherford AVA",tags:["Historic"],blurb:"Coppola's 1879 château; ivy-covered stone and flagship Rubicon Cabernet.",url:"https://www.inglenook.com"},
{id:"harlan",name:"Harlan Estate",town:"Oakville",ava:"Oakville AVA",tags:["Cult Classic"],blurb:"California 'First Growth' from an Oakville hillside; mailing-list only, waitlists span years, no walk-ins.",url:"https://harlanwinery.com"},
{id:"farniente",name:"Far Niente",town:"Oakville",ava:"Oakville AVA",tags:["Cave Tour"],blurb:"Restored 1885 stone winery, gardens, and a vast cave housing vintage automobiles.",url:"https://farniente.com"},
{id:"caymus",name:"Caymus Vineyards",town:"Rutherford",ava:"Rutherford AVA",tags:["Family"],blurb:"Five generations of the Wagner family; garden tastings of acclaimed bold Cabernets.",url:"https://caymus.com"},
{id:"beringer",name:"Beringer Vineyards",town:"St. Helena",ava:"St. Helena AVA",tags:["Historic"],blurb:"Napa's oldest continuously operating winery (1876); tour the landmark Rhine House. Easy to visit.",url:"https://www.beringer.com"},
{id:"krug",name:"Charles Krug",town:"St. Helena",ava:"St. Helena AVA",tags:["Historic","Family"],blurb:"Napa's first winery, est. 1861, run by the Peter Mondavi family.",url:"https://www.charleskrug.com"},
{id:"schramsberg",name:"Schramsberg",town:"Calistoga",ava:"Diamond Mountain",tags:["Sparkling","Cave Tour","Historic"],blurb:"Hillside caves dug by hand in the 1870s; America's benchmark traditional-method sparkling since 1862. Reservation essential.",url:"https://www.schramsberg.com"},
{id:"sterling",name:"Sterling Vineyards",town:"Calistoga",ava:"Calistoga AVA",tags:["Modern"],blurb:"Ride the aerial gondola to a white hilltop winery with 300-foot valley views.",url:"https://www.sterlingvineyards.com"},
{id:"frankfamily",name:"Frank Family Vineyards",town:"Calistoga",ava:"Calistoga AVA",tags:["Family","Historic"],blurb:"Welcoming, relaxed tastings at the historic 1884 Larkmead stone winery.",url:"https://frankfamilyvineyards.com"},
{id:"hall",name:"HALL St. Helena",town:"St. Helena",ava:"St. Helena AVA",tags:["Modern","Dog Friendly"],blurb:"Glass-and-steel winery with serious contemporary art — look for Bunny Foo Foo.",url:"https://www.hallwines.com"},
{id:"martini",name:"Louis M. Martini",town:"St. Helena",ava:"St. Helena AVA",tags:["Historic"],blurb:"Cabernet house since 1933; cellar tastings in the original winery.",url:"https://www.louismartini.com"},
{id:"heitz",name:"Heitz Cellar",town:"St. Helena",ava:"St. Helena AVA",tags:["Icon"],blurb:"Home of Martha's Vineyard Cabernet — one of Napa's most storied single-vineyard wines.",url:"https://www.heitzcellar.com"},
{id:"spottswoode",name:"Spottswoode",town:"St. Helena",ava:"St. Helena AVA",tags:["Family"],blurb:"1882 estate farmed organically; polished, intimate, family-run Cabernet.",url:"https://www.spottswoode.com"},
{id:"corison",name:"Corison Winery",town:"St. Helena",ava:"St. Helena AVA",tags:["Family"],blurb:"Cathy Corison's benchmark, age-worthy Cabernets from the Kronos Vineyard. Small and personal.",url:"https://corison.com"},
{id:"duckhorn",name:"Duckhorn Vineyards",town:"St. Helena",ava:"St. Helena AVA",tags:["Icon"],blurb:"The house that made Napa Merlot famous — Three Palms Vineyard is the flagship. Veranda tastings.",url:"https://www.duckhorn.com"},
{id:"pride",name:"Pride Mountain Vineyards",town:"Spring Mountain",ava:"Spring Mountain District",tags:["Cave Tour"],blurb:"2,000 feet up, straddling the Napa–Sonoma line; caves, big mountain reds, views. Hillside detour.",url:"https://www.pridewines.com"},
{id:"smithmadrone",name:"Smith-Madrone",town:"Spring Mountain",ava:"Spring Mountain District",tags:["Family"],blurb:"Dry-farmed mountain estate; two brothers, legendary Riesling. Mountain detour.",url:"https://www.smithmadrone.com"},
{id:"vsattui",name:"V. Sattui",town:"St. Helena",ava:"St. Helena AVA",tags:["Family","Dog Friendly"],blurb:"Picnic grounds, deli, walk-ins welcome, wines sold only direct — Napa's easiest casual stop.",url:"https://www.vsattui.com"},
{id:"phelps",name:"Joseph Phelps",town:"St. Helena",ava:"St. Helena AVA",tags:["Icon"],blurb:"Birthplace of Insignia (1974); terrace tastings with a view over the estate vineyard. Bold reds.",url:"https://www.josephphelps.com"},
{id:"bv",name:"Beaulieu Vineyard",town:"Rutherford",ava:"Rutherford AVA",tags:["Historic","Icon"],blurb:"Georges de Latour Private Reserve — Rutherford Cabernet history since 1900.",url:"https://www.bvwines.com"},
{id:"grgich",name:"Grgich Hills Estate",town:"Rutherford",ava:"Rutherford AVA",tags:["Historic"],blurb:"Founded by Mike Grgich, maker of the Paris-winning 1973 Chardonnay; farmed biodynamically.",url:"https://www.grgich.com"},
{id:"frogsleap",name:"Frog's Leap",town:"Rutherford",ava:"Rutherford AVA",tags:["Family","Dog Friendly"],blurb:"Organic, dry-farmed, refreshingly unstuffy — the red barn and gardens are a valley favourite.",url:"https://www.frogsleap.com"},
{id:"quintessa",name:"Quintessa",town:"Rutherford",ava:"Rutherford AVA",tags:["Modern"],blurb:"A single biodynamic estate; crescent-shaped winery built into the hill. Elevated seated tasting with a view.",url:"https://www.quintessa.com"},
{id:"honig",name:"Honig Vineyard & Winery",town:"Rutherford",ava:"Rutherford AVA",tags:["Family","Dog Friendly"],blurb:"Family-run and solar-powered; Sauvignon Blanc and Cabernet on a relaxed patio. Good value.",url:"https://www.honigwine.com"},
{id:"mumm",name:"Mumm Napa",town:"Rutherford",ava:"Rutherford AVA",tags:["Sparkling","Dog Friendly"],blurb:"Casual sparkling flights on a vineyard-view terrace, plus a fine-photography gallery.",url:"https://www.mummnapa.com"},
{id:"rutherfordhill",name:"Rutherford Hill",town:"Rutherford",ava:"Rutherford AVA",tags:["Cave Tour"],blurb:"Nearly a mile of caves and oak-shaded picnic grounds above the valley. Merlot specialist.",url:"https://www.rutherfordhill.com"},
{id:"nickel",name:"Nickel & Nickel",town:"Oakville",ava:"Oakville AVA",tags:["Icon"],blurb:"Single-vineyard Cabernets tasted around the 1880s Sullenger farmhouse.",url:"https://www.nickelandnickel.com"},
{id:"silveroak",name:"Silver Oak",town:"Oakville",ava:"Oakville AVA",tags:["Icon"],blurb:"Cabernet only, aged in American oak; a LEED-certified showpiece winery and crowd favourite.",url:"https://silveroak.com"},
{id:"dallavalle",name:"Dalla Valle Vineyards",town:"Oakville",ava:"Oakville AVA",tags:["Cult Classic"],blurb:"Hillside estate above Oakville; Maya is one of Napa's great wines. Allocation-focused, very limited visits.",url:"https://dallavallevineyards.com"},
{id:"eagle",name:"Screaming Eagle",town:"Oakville",ava:"Oakville AVA",tags:["Cult Classic"],blurb:"Napa's most famous cult Cabernet; NO public visits — allocation list only."},
{id:"chappellet",name:"Chappellet",town:"Pritchard Hill",ava:"Pritchard Hill",tags:["Family"],blurb:"Pritchard Hill pioneers since 1967; tastings inside the great pyramid winery. Big views, hillside detour.",url:"https://www.chappellet.com"},
{id:"continuum",name:"Continuum Estate",town:"Pritchard Hill",ava:"Pritchard Hill",tags:["Cult Classic","Modern"],blurb:"Tim Mondavi's Sage Mountain estate high on Pritchard Hill; appointment only, splurge, bold Cabernet with a view.",url:"https://continuumestate.com"},
{id:"colgin",name:"Colgin Cellars",town:"Pritchard Hill",ava:"Pritchard Hill",tags:["Cult Classic"],blurb:"IX Estate above Lake Hennessey; tiny production, storied mailing list, essentially no public visits.",url:"https://www.colgincellars.com"},
{id:"promontory",name:"Promontory",town:"Oakville",ava:"Napa Valley",tags:["Cult Classic","Modern"],blurb:"The Harlan family's monumental territory in the hills west of Oakville; by invitation, splurge."},
{id:"shafer",name:"Shafer Vineyards",town:"Napa",ava:"Stags Leap District",tags:["Icon"],blurb:"Hillside Select — a defining Stags Leap Cabernet; intimate appointment tastings, splurge-worthy.",url:"https://shafervineyards.com"},
{id:"closduval",name:"Clos Du Val",town:"Napa",ava:"Stags Leap District",tags:["Historic","Dog Friendly"],blurb:"French-accented estate, est. 1972; poured at the Judgment of Paris.",url:"https://www.closduval.com"},
{id:"chimneyrock",name:"Chimney Rock",town:"Napa",ava:"Stags Leap District",tags:["Icon"],blurb:"White Cape Dutch estate beneath the Stags Leap palisades; polished Cabernet flights.",url:"https://www.chimneyrock.com"},
{id:"pineridge",name:"Pine Ridge Vineyards",town:"Napa",ava:"Stags Leap District",tags:["Cave Tour"],blurb:"Cave tastings carved beneath the Stags Leap hillsides.",url:"https://www.pineridgevineyards.com"},
{id:"silverado",name:"Silverado Vineyards",town:"Napa",ava:"Stags Leap District",tags:["Family"],blurb:"Founded by the Disney family; sweeping views across Stags Leap, friendly service.",url:"https://www.silveradovineyards.com"},
{id:"darioush",name:"Darioush",town:"Napa",ava:"Napa Valley",tags:["Modern"],blurb:"Persepolis-inspired columns and plush seated Bordeaux-variety tastings on the Silverado Trail. Dramatic.",url:"https://www.darioush.com"},
{id:"jarvis",name:"Jarvis Estate",town:"Napa",ava:"Napa Valley",tags:["Cave Tour"],blurb:"The entire winery lives inside a 45,000-sq-ft cave — waterfall included. Unique, splurge.",url:"https://www.jarviswines.com"},
{id:"hess",name:"Hess Persson Estates",town:"Mount Veeder",ava:"Mount Veeder AVA",tags:["Modern"],blurb:"Mountain winery paired with a world-class contemporary art museum. Worth the drive."},
{id:"trefethen",name:"Trefethen Family Vineyards",town:"Napa",ava:"Oak Knoll District",tags:["Historic","Family","Dog Friendly"],blurb:"1886 gravity-flow wooden winery; estate-grown everything in Oak Knoll. Welcoming.",url:"https://www.trefethen.com"},
{id:"chandon",name:"Domaine Chandon",town:"Yountville",ava:"Yountville AVA",tags:["Sparkling"],blurb:"Moët's first American sparkling house (1973); garden lounges, walkable from Yountville dining.",url:"https://www.chandon.com"},
{id:"clifflede",name:"Cliff Lede Vineyards",town:"Yountville",ava:"Stags Leap District",tags:["Modern"],blurb:"Rock-and-roll vineyard blocks, an art gallery, and lively Stags Leap Cabernets. Fun.",url:"https://cliffledevineyards.com"},
{id:"artesa",name:"Artesa",town:"Napa",ava:"Carneros AVA",tags:["Modern"],blurb:"Minimalist hilltop winery sunk into a Carneros ridge; bay-view terraces, a sunset spot.",url:"https://www.artesawinery.com"},
{id:"cade",name:"CADE Estate",town:"Howell Mountain",ava:"Howell Mountain AVA",tags:["Modern"],blurb:"Organically farmed, LEED Gold estate at 1,800 feet with huge valley views. Mountain detour.",url:"https://www.cadewinery.com"}
];
var NW_RESTAURANTS=[
{id:"frenchlaundry",name:"The French Laundry",town:"Yountville",note:"3 Michelin ★ · Thomas Keller · books months ahead · ultimate splurge"},
{id:"auberge",name:"Auberge du Soleil",town:"Rutherford",note:"Michelin ★ · hilltop terrace · the most romantic lunch in the valley"},
{id:"press",name:"PRESS",town:"St. Helena",note:"Michelin ★ · wood-fired grill · 3,000-bottle Napa list including cult wines"},
{id:"bouchon",name:"Bouchon Bistro",town:"Yountville",note:"Classic French bistro · Keller precision · dog-friendly patio"},
{id:"charteroak",name:"The Charter Oak",town:"St. Helena",note:"Live-fire, communal dining"},
{id:"jeanty",name:"Bistro Jeanty",town:"Yountville",note:"Champagne-region French · cosy · more affordable · dog-friendly patio"},
{id:"adhoc",name:"Ad Hoc + Addendum",town:"Yountville",note:"Family-style · Monday fried chicken"},
{id:"gotts",name:"Gott's Roadside",town:"St. Helena",note:"Classic burgers · perfect casual mid-route refuel · dog-friendly outdoor seating"},
{id:"mustards",name:"Mustards Grill",town:"Yountville",note:"The original wine-country roadhouse, est. 1983"}
];
if(typeof module!=='undefined'&&module.exports){module.exports={WINERIES:NW_WINERIES,RESTAURANTS:NW_RESTAURANTS};}
